name: "Jozef Izso on GitHub"
description: ""

url: "jozefizso.github.io"

exclude: ["readme.md", "x"]

markdown: kramdown
highlighter: rouge

safe: true
lsi: false


author:
  name: Jozef Izso
  email: jozef.izso@gmail.com
  github: jozefizso
